image: node:16.20.2

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - node downloadSecureFiles.js
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test
  dependencies:
    - setup