image: node:16.20.2

stages:
  - setup
  - test

setup:
  stage: setup
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.'
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm run all
  dependencies:
    - setup