image: node:16.20.2

stages:
  - setup
  - test

cache:
  paths:
    - node_modules/

download_secure_files:
  stage: setup
  script:
    - node downloadSecureFiles.js

install_dependencies:
  stage: setup
  script:
    - npm ci

test:
  stage: test
  script:
    - npm run all